baseURL = "https://laurenar.net/"
languageCode = "en-us"
title = "Lauren's Blog"

theme = "cactus"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]

  colortheme = "light" # dark, light, white, or classic
  enableEmoji = true
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  css = ["css/custom.css"]

  # Home page settings
  description = "Hello! My name is Lauren Arnett. I am a computer programmer living in NYC interested in backend development. In 2021, I attended a batch at [Recurse Center](https://www.recurse.com/), where I focused on studying Haskell, distributed systems, and SIMD parallelism. \n\n I also tutor programming to middle school-age students virtually."

  mainSection = "posts" # your main section
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default
  # add math
  mathjax = true

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/laurenarnett"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/lauren-arnett-6ab037117/"
  [[params.social]]
    name = "email"
    link = "lauren.arnett1@gmail.com"  # no need for "mailto:" in the head


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
